# Generated by Django 3.1.7 on 2021-06-07 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passinger_name', models.CharField(max_length=250)),
                ('bus_number', models.CharField(max_length=50)),
                ('pickup_point', models.CharField(max_length=250)),
                ('droping_point', models.CharField(max_length=250)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('number', models.CharField(max_length=30)),
                ('capacity', models.IntegerField()),
                ('fair', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('phone', models.IntegerField()),
                ('dob', models.DateField()),
                ('address', models.TextField(blank=True, default='')),
                ('is_driver', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=250)),
                ('destination', models.CharField(max_length=250)),
                ('no_of_kms', models.IntegerField()),
                ('status', models.CharField(choices=[('draft', 'draft'), ('inprogress', 'inprogress'), ('done', 'done'), ('cancel', 'cancel')], max_length=250)),
                ('Passengers', models.ManyToManyField(related_name='trip_passengers', to='bus.Passenger')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bus.passenger')),
            ],
        ),
    ]
