# Generated by Django 3.1.7 on 2021-06-07 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bus',
        ),
    ]
